### ISSUE TITLE
get_largest_cros_blockdev fails in pre-frecon shims

### ISSUE THREAD

**Issue by ZeglolTheThirtySixth** [CoolElectronics/sh1mmer.me#144]
On all devices i've tested that are pre-frecon, get_largest_cros_blockdev completely fails, and every action that uses it (cryptosmite, disabling rootfs verification, touching .developer_mode, etc) exits complaining about the internal storage not having a ChromeOS install.

This has mostly been tested on Kefka, and I have not encountered this error when running a frecon shim (e.g. octopus, legacy sh1mmer doesn't change anything), and I'm not entirely sure what the cause is as I haven't done much testing, though if I had to guess it's likely an outdated or missing binary for sfdisk.

**Comment by BinBashBanana** [comment]
Can you send the output of `sfdisk -l -o name /dev/mmcblk0`

**Comment by ZeglolTheThirtySixth** [comment]
I was right, running sfdisk with those arguments shows "invalid option -- 'o'" and the rest of the sfdisk help menu. This was tested on the shim and in a chroot for the screenshot.
![Screenshot 2024-08-13 at 3 51 07 PM](https://github.com/user-attachments/assets/7e7387a6-5d43-4dac-b912-83f83e9079ce)

**Comment by DJ-Laser** [comment]
This seems to work in the coral shim, sfdisk lists the -o option in the help menu, but I haven't tested any of the payloads. I'll try to cryptosmite a hana Chromebook soon, I'll comment the results here.

**Comment by BinBashBanana** [comment]
should be resolved now :D

**Comment by ZeglolTheThirtySixth** [comment]
@BinBashBanana Tested on latest commit, the issue still persists with all usages of get_largest_cros_blockdev continuining to return "No CrOS SSD found on device!"

**Comment by BinBashBanana** [comment]
Is ChromeOS installed on the internal drive? It won't find it without. If it is, can you send the output of `sfdisk -d /dev/mmcblk0`

**Comment by ZeglolTheThirtySixth** [comment]
```
localhost / # sfdisk -d /dev/mmcblk0
# partition table of /dev/mmcblk0
unit: sectors

/dev/mmcblk0p1 : start=          1, size= 61071359, Id=ee
/dev/mmcblk0p2 : start=          0, size=               0, Id= 0
/dev/mmcblk0p3 : start=          0, size=               0, Id= 0
/dev/mmcblk0p4 : start=          0, size=               0, Id= 0
```
@BinBashBanana 
A full stock ChromeOS is installed on the internal drive

**Comment by BinBashBanana** [comment]
Uh oh... looks like sfdisk didn't used to support GPT. I'll have to use cgpt instead.

**Comment by yalelhoel** [comment]
confirmed on octopus, attempted to use a legacy shim all i was greeted with when trying to use pretty much every option was, something complaining about no chromeos install

**Comment by yalelhoel** [comment]
confirmed on octopus, attempted to use a legacy shim all i was greeted with when trying to use pretty much every option was, something complaining about no chromeos install

**Comment by ZeglolTheThirtySixth** [comment]
I don't think octopus is affected by this issue as its shim was made at R72, the main device i've done my testing on is kefka, which was made for R48, the function relies on the presence of a ChromeOS install on the disk so if you didn't have one it won't work either way.

**Comment by yalelhoel** [comment]
i do have a chromeos install, it may just be that i frankensteined this shim together but from what i see, i have all dependencies

**Comment by yalelhoel** [comment]
yeah no, it just doesn't work, and for seemingly no reason

**Comment by BinBashBanana** [comment]
You need ChromeOS installed on the disk for it to work.

**Comment by BinBashBanana** [comment]
Misread, can you send the output of `sfdisk -l /dev/mmcblk0`

**Comment by BinBashBanana** [comment]
@ZeglolTheThirtySixth static sfdisk will be bundled instead, as there are other functions that rely on sfdisk as well.

**Comment by yalelhoel** [comment]
as i said, chromeos is installed

**Comment by yalelhoel** [comment]
dont have access to the computer rn

**Comment by yalelhoel** [comment]
got the computer, it does indeed have chromeos installed on the mmc card **in the chromebook** it is in fact booted into chromeos currently

**Comment by ZeglolTheThirtySixth** [comment]
Issue is over a year old lol
